# Data Analysis Test

Use file `./ref/crop_data.csv` for input

Use `pandas` lib

Write your code and display readable result

In [1]:
import pandas as pd

In [3]:
# read csv file

df = pd.read_csv("./ref/crop_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   crop_year         11914 non-null  object 
 1   year              11914 non-null  int64  
 2   product           11914 non-null  object 
 3   province          11914 non-null  object 
 4   area_plant_rai    11769 non-null  float64
 5   area_harvest_rai  11728 non-null  float64
 6   production_ton    11692 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 651.7+ KB


### Example Question

How many "ยางพารา" produced in whole country ("ทั้งประเทศ")


In [4]:
# How many "ยางพารา" produced in whole country ("ทั้งประเทศ")
new_df = df.loc[
    (df["product"] == "ยางพารา" ) &
    (df["province"] == "ทั้งประเทศ") 
]
sum(new_df["production_ton"])


47686839.0

### Question 1

How many "ข้าวนาปี" produced in "ยะลา" between year 2550 - 2553


In [18]:
# Write you code and display question 1 result here.
q1_df = df.loc[(df['product'] == "ข้าวนาปี") & (df['province'] == "ยะลา")]
sum_q1 = sum(q1_df["production_ton"])
print(f"There are {sum_q1} tons of ข้าวนาปี produced in ยะลา")

There are 186830.0 tons of ข้าวนาปี produced in ยะลา


### Question 2

Calculate harvest rate of "ข้าวนาปี" in whole country

_harvest rate = area_harvest_rai / area_plant_rai_

In [59]:
df_q2 =  df.loc[(df['product'] == "ข้าวนาปี") & (df['province'] == "ทั้งประเทศ")]

In [61]:
# Write you code and display question 2 result here.
# replace with your code
area_harvest_rai = sum(df_q2['area_harvest_rai'])
area_plant_rai = sum(df_q2['area_plant_rai'])
harvest_rate = area_harvest_rai / area_plant_rai

print('area_harvest_rai', area_harvest_rai)
print('area_plant_rai', area_plant_rai)
print('harvest_rate', harvest_rate)

area_harvest_rai 730340255.0
area_plant_rai 783456906.0
harvest_rate 0.9322022046225986


### Question 3

Calculate total profit of "ข้าวโพดฝักอ่อน" produced in "ภาคเหนือ" from year 2555 to 2562
- profit rate in year 2555 - year 2559 is 50% (selling price is 50THB/kg.)
- profit rate in year 2560 - year 2562 is 30% (selling price is 120THB/kg.)
- assume all product was sold out every year.


In [62]:
df.head()

crop_year  year   product    province  area_plant_rai  area_harvest_rai  \
0   2549/50  2550  ข้าวนาปี  ทั้งประเทศ      57541825.0        53500163.0   
1   2550/51  2551  ข้าวนาปี  ทั้งประเทศ      57385921.0        53892143.0   
2   2551/52  2552  ข้าวนาปี  ทั้งประเทศ      57422337.0        54385144.0   
3   2552/53  2553  ข้าวนาปี  ทั้งประเทศ      57497441.0        54739638.0   
4   2553/54  2554  ข้าวนาปี  ทั้งประเทศ      64574071.0        59690203.0   

   production_ton  
0      23108401.0  
1      23582596.0  
2      23508833.0  
3      23430770.0  
4      25742917.0

In [69]:
# Write you code and display question 3 result here.

df_corn_north = df.loc[(df['product'] == "ข้าวโพดฝักอ่อน") & (df['province'] == "ภาคเหนือ")]
df_corn_2555to2559 = df_corn_north.loc[(df_corn_north['year'] >= 2555) & (df_corn_north['year'] <= 2559)]
df_corn_2560to2562 = df_corn_north.loc[(df_corn_north['year'] >= 2560) & (df_corn_north['year'] <= 2562)]


profit_rate_55to59 = (sum(df_corn_2555to2559['production_ton']) * 1000) * 50 * 0.5
profit_rate_59to62 = (sum(df_corn_2560to2562['production_ton']) * 1000) * 120 * 0.3
total_profit = profit_rate_55to59 + profit_rate_59to62

print(f"Total profit of ข้าวโพดฝักอ่อน from 2555 to 2562 is {total_profit} THB")

Total profit of ข้าวโพดฝักอ่อน from 2555 to 2562 is 5076935000.0 THB


### Question 4

Form question 3, display the dataframe with 'year', 'production_ton', 'income', 'profit_thb' column


In [ ]:
# filtered only ภาคเหนือ already

df_corn_2555to2559 = df_corn_2555to2559.assign(
    income=df_corn_2555to2559['production_ton'] * 1000 * 50,
    profit_thb=(df_corn_2555to2559['production_ton'] * 1000 * 50 * 0.5)
)
df_corn_2560to2562 = df_corn_2560to2562.assign(
    income=df_corn_2560to2562['production_ton'] * 1000 * 120,
    profit_thb=(df_corn_2560to2562['production_ton'] * 1000 * 120 * 0.3)
)


df_result = pd.concat([df_corn_2555to2559, df_corn_2560to2562])
df_result = df_result[['year', 'production_ton', 'income', 'profit_thb']]

print(df_result)

       year  production_ton        income   profit_thb
11690  2555         24741.0  1.237050e+09  618525000.0
11691  2556         25371.0  1.268550e+09  634275000.0
11692  2557         21788.0  1.089400e+09  544700000.0
11693  2558         20499.0  1.024950e+09  512475000.0
11694  2559         19332.0  9.666000e+08  483300000.0
11695  2560         21329.0  2.559480e+09  767844000.0
11696  2561         21757.0  2.610840e+09  783252000.0
11697  2562         20349.0  2.441880e+09  732564000.0


### Question 5

We plan to invest in growing soybeans (ถั่วเหลือง) which province should we invest.

We looking for
- high protential area (high havest_rate)
- we want market share only 20% but production_ton should be more than 2000 in the past (2550 - 2562)



In [99]:
# Write you code and display question 5 result here.

# Assume that "invest in growing" means "which province (that already grown soybean) should we invest" not "which province from whole country should we invest"


df_soybean = df.loc[(df['product'] == 'ถั่วเหลือง') & 
                    (df['year'] >= 2550) & (df['year'] <= 2562) & 
                    ~df['province'].isin(['ทั้งประเทศ', 'ภาคเหนือ', 'ภาคตะวันออกเฉียงเหนือ', 'ภาคกลาง', 'ภาคใต้'])].copy()
df_soybean['harvest_rate'] = df_soybean['area_harvest_rai'] / df_soybean['area_plant_rai']

province_summary = df_soybean.groupby('province').agg(
    total_production=('production_ton', 'sum'),
    average_harvest_rate=('harvest_rate', 'mean')
).reset_index()

total_production_all = df_soybean['production_ton'].sum()
province_summary['market_share'] = (province_summary['total_production'] / total_production_all) * 100
filtered_provinces = province_summary[(province_summary['total_production'] > 2000) & (province_summary['market_share'] <= 20)] # filter

filtered_provinces = filtered_provinces.sort_values(by='average_harvest_rate', ascending=False)
print(filtered_provinces.head(10))






top_3_provinces = filtered_provinces.sort_values(by='average_harvest_rate', ascending=False).head(3)
top_3_names = ', '.join(top_3_provinces['province'])
print(f"Top 3 provinces that we should invest in growing soybeans are {top_3_names}.")

      province  total_production  average_harvest_rate  market_share
31        แพร่        124649.000              0.994117      9.038104
32  แม่ฮ่องสอน        216298.000              0.991509     15.683429
5   ฉะเชิงเทรา          8038.000              0.990072      0.582823
17       ลำพูน          3471.967              0.989412      0.251747
27    เชียงราย         68852.000              0.988140      4.992351
29   เพชรบูรณ์          8959.000              0.984938      0.649603
28   เชียงใหม่        180564.000              0.984715     13.092413
9         น่าน         61758.000              0.981751      4.477976
7          ตาก         71097.000              0.981378      5.155132
4     จันทบุรี          3953.000              0.980721      0.286626
Top 3 provinces that we should invest in growing soybeans are แพร่, แม่ฮ่องสอน, ฉะเชิงเทรา.
